version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "./backend/package-lock.json" }}-{{ checksum "./frontend/package-lock.json" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "./backend/package-lock.json" }}-{{ checksum "./frontend/package-lock.json" }}
          paths:
            - "venv"
            - ./backend/node_modules
            - ./frontend/node_modules
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 tests.py
      - store_artifacts:
          path: test-reports/
          destination: python_app
